### PR TITLE
Fixed very werid query that was fetching the tax data in a very inefficient manner

### PR DESCRIPTION
**Pull request by edwinknol-mediact**
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [ X ] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ X ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

See https://jira.tig.nl/projects/BUCKM1/issues/BUCKM1-465?filter=allopenissues

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood]. Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

### CODE REVIEW

**Comment by jasperzeinstra** [comment]
@tigsupport @tig-robertgrundeken Waarom pakken jullie dit niet verder op?

**Comment by tig-robertgrundeken** [comment]
@jasperzeinstra Thank you for focussing on this issue. We are sad that it took such a long time. We solved this issue internally on the 13th of February 2018 and contacted your colleagues with the new version of the query to test it with the large dataset. We never had any response. Meanwhile this ticket has been multiple times added, and revoked by @edwinknol-mediact. On 8th of March we handed it over to Buckaroo Support, with the solution. 

@edwinknol-mediact @jasperzeinstra This is the code which is working stable in the production environment for your client with the large dataset? Then we will add it to the extension and run the tests on it.

Hopefully in the future we can speed up this process, always looking to improve things.

**Comment by jasperzeinstra** [comment]
@tig-robertgrundeken we provided the fix, we're already using this fix in a fork. The current collection is way to big for large shops. It's fetching the data in a weird matter. So please fix this in your upcoming release so it's more stable/faster for bigger shops.

It's also weird that a Pull Request is open for so long. Maybe you guys could check GitHub more often.

**Comment by tig-robertgrundeken** [comment]
Thank you for your constructive feedback we will take this into account!

**Comment by tig-robertgrundeken** [comment]
This fix was added in v4.20. Thanks for the input and i'm closing it here.

**Pull request closed without merging**
